# Generated by Django 3.1.4 on 2020-12-05 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=50)),
                ('nombrecompleto', models.CharField(max_length=80)),
                ('correo', models.CharField(max_length=30)),
                ('contraseña', models.CharField(max_length=30)),
                ('documento', models.IntegerField()),
                ('telefono', models.IntegerField()),
            ],
        ),
    ]
